version: '3.3'
services:
  vault:
    image: vault:1.0.1
    cap_add:
        - IPC_LOCK
    environment:
        VAULT_ADDR: "0.0.0.0:8200"
        VAULT_DEV_ROOT_TOKEN_ID: "poc-vault-token"
    ports:
        - "8200:8200"
  strongswan:
    build: strongswan
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/udp"
    privileged: true
    volumes:
      - "charondata:/var/run"
  service:
    build: .
    volumes:
      - ".:/app"
      - "charondata:/var/run"
    environment:
        VAULT_TOKEN: "poc-vault-token"
        VAULT_ENDPOINT: "http://vault:8200"
    depends_on:
      - strongswan
      - vault

volumes:
  charondata:
